name: CI - React Native Expo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Navigate to project directory
        run: cd test

      # Stap 3: Installeer dependencies
      - name: Install dependencies
        run: npm install

      # Stap 4: Controleer de build
      - name: Run Expo build
        run: npm run expo:build
