name: CI - React Native Expo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Installeer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      # Stap 3: Installeer projectafhankelijkheden
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/StickerSmash
        run: npm install

      # Stap 4: Voer tests uit
      - name: Run Tests
        working-directory: ${{ github.workspace }}/StickerSmash
        run: npm run test

  maestro-cloud:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Stap 1: Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Download de APK via de opgeslagen URL
      - name: Download APK file
        run: |
          curl -o app-release.apk "${{ secrets.APK_URL }}"

      # Stap 3: Controleer of APK is gedownload
      - name: Verify APK
        run: |
          if [ -f app-release.apk ]; then
            echo "APK file successfully downloaded."
          else
            echo "APK file missing!"
            exit 1
          fi

      # Stap 4: Pak de APK in een ZIP-bestand
      - name: Package APK in ZIP file
        run: |
          zip app-release.zip app-release.apk

      # Stap 5: Controleer of ZIP-bestand is aangemaakt
      - name: Verify ZIP file
        run: |
          if [ -f app-release.zip ]; then
            echo "ZIP file successfully created."
          else
            echo "ZIP file missing!"
            exit 1
          fi

      # Stap 6: Run Maestro Cloud Test
      - name: Run Maestro Cloud Test
        uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: app-release.zip
          name: "Explore Test"
          async: true
