name: CI - React Native Expo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Installeer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      # Stap 3: Installeer Expo CLI en EAS CLI
      - name: Install Expo CLI and EAS CLI
        run: |
          npm install -g expo-cli eas-cli

      # Stap 4: Stel Expo token in
      - name: Set Expo token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Stap 5: Installeer projectafhankelijkheden
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/StickerSmash
        run: npm install

      # Stap 6: Voer tests uit
      - name: Run Tests
        working-directory: ${{ github.workspace }}/StickerSmash
        run: npm run test

      # Stap 7: Bouw APK met EAS
      - name: Build APK with EAS
        working-directory: ${{ github.workspace }}/StickerSmash
        run: |
          eas build --platform android --profile production --non-interactive

      # Stap 8: Haal de response van de laatste build op
      - name: Log eas build response
        working-directory: ${{ github.workspace }}/StickerSmash
        run: |
          eas build:list --limit 1 --status finished --json --non-interactive

      # Stap 9: Test of `jq` werkt
      - name: Test jq
        working-directory: ${{ github.workspace }}/StickerSmash
        run: |
          eas build:list --limit 1 --status finished --json --non-interactive | jq .

      # Stap 10: Haal build URL op met jq
      - name: Haal het buildUrl op met jq
        working-directory: ${{ github.workspace }}/StickerSmash
        run: |
          BUILD_URL=$(eas build:list --limit 1 --status finished --json --non-interactive | jq -r '.[0].artifacts.buildUrl')
          echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV

      # Stap 11: Download APK bestand
      - name: Download APK file
        run: |
          curl -o app-release.apk "$BUILD_URL"

      # Stap 12: Run Maestro Cloud Test
      - name: Run Maestro Cloud Test
        uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: app-release.apk
          name: "Explore Test"
          async: true
