name: CI - React Native Expo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # Controleer huidige mapstructuur
      - name: Debug current directory
        run: ls -R ${{ github.workspace }}

      - name: Adjust directory if double nested
        run: |
          if [ -d "${{ github.workspace }}/test" ]; then
            mv ${{ github.workspace }}/test/* ${{ github.workspace }}
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm install

      - name: Run Expo build
        run: npm run expo:build
