name: CI - React Native Expo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Installeer Node.js en dependencies
      - name: Set up Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/StickerSmash
        run: npm install

      # Stap 3: Installeer Expo CLI en EAS CLI
      - name: Install Expo CLI and EAS CLI
        run: |
          npm install -g expo-cli eas-cli

      # Stap 4: Bouw APK met EAS
      - name: Build APK with EAS
        working-directory: ${{ github.workspace }}/StickerSmash
        run: |
          eas build --platform android --profile production --non-interactive

      # Stap 5: Haal build URL op
      - name: Retrieve build URL
        working-directory: ${{ github.workspace }}/StickerSmash
        run: |
          BUILD_URL=$(eas build:list --limit 1 --status finished --json --non-interactive | jq -r '.[0].artifacts.buildUrl')
          echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV

      # Stap 6: Download APK bestand
      - name: Download APK
        run: |
          curl -o app-release.apk "$BUILD_URL"

      # Stap 7: Run Maestro Cloud Test
      - name: Run Maestro Cloud Test
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: app-release.apk
